chaoss/chaoss-slack-bot

.gitignore
.vscode/settings.json
_tests_/app.test.js
app.js
package-lock.json
package.json

initial commit

---

app.js

Signed-off-by: mide358 <iyimide.adegunloye@gmail.com>

Enabled bot to send message to new members

---

README.md
_tests_/app.test.js
app.js

- Fixed mentorship program response
- Increased test coverage
- Updated readme

Updated "team_join" event listener

---

Procfile

Signed-off-by: mide358 <iyimide.adegunloye@gmail.com>

Added Profile file

---

app.js

Signed-off-by: dotun2203 <adedotunabimbola2@gmail.com>

chaoss bot welcome message updated

---

app.js

Signed-off-by: mide358 <iyimide.adegunloye@gmail.com>

edited styling

---

app.js
components/africa.js

This PR adds a feature that sends a DM about CHAOSS Africa when a user types the keyword "africa-info".
Closes #24

implemented chaoss africa keyword triggered DM

---

app.js
components/joinChannel.js
components/joinChaossAfrica.js

Hello, I've created the feature. Please, let me know if I need to make any changes. I await your feedback. Thank you.

create new component-joinChaossAfrica, that sends message to newcomers

---

app.js
components/chaossAfrica/africa.js
components/chaossAfrica/joinChaossAfrica.js

fixed chaoss-africa DM bugs

---

app.js

PR fixes import error that was causing the app to crash.
Signed-off-by: Precious Abubakar <preciousdanabubakar@gmail.com>

fix module import error

---

.github/ISSUE_TEMPLATE/bug-report.yml

Signed-off-by: Precious Abubakar <preciousdanabubakar@gmail.com>

bug report template

---

.github/ISSUE_TEMPLATE/bug-report.yml

Signed-off-by: Precious Abubakar <preciousdanabubakar@gmail.com>

bug report edit

---

.github/ISSUE_TEMPLATE/bug-report.yml

Signed-off-by: Precious Abubakar <preciousdanabubakar@gmail.com>

bug report update

---

components/outreachyPrompt.js

Signed-off-by: Parth Nanda <parthnanda002@gmail.com>
This PR...
-Added one if-else statement
Second Last one is when outreachy status=true
Last one is when outreachy status=false
Fixes #

Turned off Outreachy Prompt when status is not true

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
README.md

Updating Code of Conduct link to point at https://github.com/chaoss/.github/blob/main/CODE_OF_CONDUCT.md
Files Edited : 
1-> bug-report.yml
2-> feature.yml
3-> README.md
-

#63 Issue: Updating Code of Conduct link

---

Translations/French/Basic Information.md
Translations/French/Bot Token Scopes.md
Translations/French/Community Resources.md
Translations/French/Contribution Guide.md
Translations/French/Event Subscriptions.md
Translations/French/Getting Started With Bolt For Javascript.md
Translations/French/Home.md
Translations/French/Technical Resources.md
Translations/Portuguese/Basic Information.md
Translations/Portuguese/Bot Token Scopes.md
Translations/Portuguese/Community Resources.md
Translations/Portuguese/Contribution Guide.md
Translations/Portuguese/Event Subscriptions.md
Translations/Portuguese/Getting Started With Bolt For Javascript.md
Translations/Portuguese/Home.md
Translations/Portuguese/Technical Resources.md

This PR... 
Created translation folders for the Angolan open source partnership translation and the upcoming french translation

[Feature]:Translation Files For French and Portuguese Signed-off-by: Busayo Ojo ojobusayo99@gmail.com

---

Translations/Readme.md

This PR...
- Created a Readme.md file for translations
(prefer animated gif)
Fixes #

Created Readme.md file

---

Translations/Portuguese/Basic Information.md
Translations/Portuguese/Getting Started With Bolt For Javascript.md

This PR is a translation work.
- Translation from English to Portuguese of the Getting Started With Bolt for JavaScript  page issue #90 
Fixes #

translation getting started with bolt for javascript

---

CONTRIBUTING.md
Translations/Portuguese/Home.md

This PR is an updated document work
- Additional content to explain how to contribute to the wiki issue #98 
Fixes #

Contributing to the wiki

---

Translations/Portuguese/Event Subscriptions.md

This PR Fixes #86 
- This just resolves the merge conflicts in [this pull request](https://github.com/chaoss/chaoss-slack-bot/pull/96) made by [Francisco-dos-Santos](https://github.com/Francisco-dos-Santos).

Translate the Event Subscription Page into portuguese

---

app.js

This PR...
- Created CHAOSS Meeting Notes Slack Bot
(prefer animated gif)
Fixes #

Added meeting notes slack bot
